name: run react
on:
  push:
    branches:
      - 'Dev'

jobs:
  deploy-react-to-gh-pages:
    runs-on: ubuntu-latest
    
    steps:
        
      - name: Checkout
        uses: actions/checkout@v2


      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "18.16.1"
          
      - name: Install dependencies
        run: npm install
        working-directory: ./client 


      - name: Build
        run: npm run build
        working-directory: ./client 

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/build
