name: Deploy Backend to EC2

on:
  push:
    branches:
      - Dev
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Deploy Server
        run: |
          scp -r ./server/* ${{ secrets.IAM_USERNAME }}@${{ secrets.HOST_DNS }}:
          # Restart PM2 (replace your-app-name)
          # ssh ec2-user@ec2-ip "pm2 restart your-app-n"








