name: Build React App

on:
  push:
    branches:
      - Dev

jobs:
  build:
    runs-on: ubuntu-latest

     steps:
    - name: Clear Node.js Cache
      run: npm cache clean -f

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm install

    - name: Build React App
      run: npm run build
      working-directory: ./client
